### ISSUE TITLE
use `nb_conda_kernels` instead of installing each kernel manually

### ISSUE THREAD

**Issue by aryarm** [ucsd-ets/cmm262-notebook#10]
`nb_conda_kernels` has more features, for ex: it would allow us to run tools installed in those environments using `%%bash` from within the notebooks

we just need to install it within whatever environment has `jupyterlab` installed. Our Dockerfile seems to use [this one](https://github.com/jupyter/docker-stacks/blob/5a67b4e868cd4b243ac83b1a7d39b2b080e4eff6/base-notebook/Dockerfile#L142) as its primary base image, which seems to install `jupyterlab` in the _base_ environment. So all we need to do is add this to the Dockerfile:
```
mamba install -y -c conda-forge nb_conda_kernels
```

**Comment by aryarm** [comment]
@wesuuu , I noticed this is also listed as a best practice in your [additional information doc](https://github.com/ucsd-ets/datahub-example-notebook/blob/master/additional-information.md)

Does our base Docker container already have `nb_conda_kernels` or should we install it? If it's the latter, do you know if this is the right command to install it?

**Comment by wesuuu** [comment]
I don't see it in any of our standard images https://github.com/ucsd-ets/datahub-docker-stack/wiki/Stable-Tag so yeah, just try adding it with mamba like you outlined above.
