### ISSUE TITLE
allow PRs from fork to run CI with secrets

### ISSUE THREAD

**Issue by aryarm** [ucsd-ets/cmm262-notebook#9]
PRs from forks do not have access to Github action secrets ([source](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)). This means that all PRs from a fork will fail to build.

It would be nice if there was a way to whitelist the [TA fork of this repository](https://github.com/biom262/cmm262-notebook) so that secrets could be made available to it. This is particularly important because the TAs of the class change each year, and we would like to be able to allow the new TAs to commit to this repo without having to ask the DataHub team for push-access each year.

It would also be nice if there was a way to whitelist merges from our fork. I believe this is possible through a system similar to that of the `conda-forge` Github organization.

**Comment by wesuuu** [comment]
See https://github.com/ucsd-ets/cmm262-notebook/pull/11

This will use `ghcr.io` as a image repository rather than docker. A unique `ghcr` image package is available for every fork.

**Comment by aryarm** [comment]
closing b/c of #11
